"use client";

import { useMemo, useState } from "react";
import { BedDouble, Car, Compass, ImagePlus, MapPinned, Pencil, Plus, Search, Sparkles, Trash2, X } from "lucide-react";

export type InventoryItem = { id:number; type:"hotel"|"car"|"area"|"experience"; name:string; location:string; description:string; price:number|null; status:"draft"|"active"|"archived"; imageKey:string|null; createdAt:string; updatedAt:string };
const blank={type:"hotel",name:"",location:"",description:"",price:"",status:"draft",imageKey:""};
const types=["hotel","car","area","experience"] as const;
const labels={hotel:"Hotels",car:"Cars",area:"Areas",experience:"Experiences"};
const icons={hotel:BedDouble,car:Car,area:MapPinned,experience:Sparkles};

export function InventoryManager({initialItems,userName}:{initialItems:InventoryItem[];userName:string}){
 const [items,setItems]=useState(initialItems),[type,setType]=useState("all"),[query,setQuery]=useState(""),[editing,setEditing]=useState<InventoryItem|null>(null),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[deleteId,setDeleteId]=useState<number|null>(null);
 const filtered=useMemo(()=>items.filter(i=>(type==="all"||i.type===type)&&`${i.name} ${i.location}`.toLowerCase().includes(query.toLowerCase())),[items,type,query]);
 const counts=Object.fromEntries(types.map(k=>[k,items.filter(i=>i.type===k).length]));
 const startCreate=()=>{setEditing(null);setForm(blank);setMessage("");setOpen(true)};
 const startEdit=(i:InventoryItem)=>{setEditing(i);setForm({type:i.type,name:i.name,location:i.location,description:i.description,price:i.price?.toString()??"",status:i.status,imageKey:i.imageKey??""});setMessage("");setOpen(true)};
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{const data=new FormData(event.currentTarget),image=data.get("image");let imageKey=form.imageKey;if(image instanceof File&&image.size){const upload=new FormData();upload.append("image",image);const response=await fetch("/api/upload",{method:"POST",body:upload});const result=await response.json() as {key?:string;error?:string};if(!response.ok)throw new Error(result.error);imageKey=result.key??imageKey}const payload={...form,imageKey,price:form.price,...(editing?{id:editing.id}:{})};const response=await fetch("/api/inventory",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error);window.location.reload()}catch(error){setMessage(error instanceof Error?error.message:"Could not save this item.");setBusy(false)}}
 async function remove(id:number){setBusy(true);const response=await fetch(`/api/inventory?id=${id}`,{method:"DELETE"});if(response.ok){setItems(c=>c.filter(i=>i.id!==id));setDeleteId(null)}else setMessage("Could not delete this item.");setBusy(false)}
 return <div className="admin-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Compass size={23}/></span><span>Amaravathi<small>Travel admin</small></span></div><nav aria-label="Admin navigation"><a className="nav-active" href="#inventory"><MapPinned size={19}/>Inventory</a><a href="https://amaravati-journeys-atelier.psri38157.chatgpt.site" target="_blank" rel="noreferrer"><Compass size={19}/>View website</a></nav><div className="user-card"><span>{userName?.charAt(0)||"A"}</span><div><strong>{userName||"Administrator"}</strong><small>Site owner</small></div></div></aside>
 <main><header className="topbar"><div><p>Operations dashboard</p><h1>Travel inventory</h1></div><a className="signout" href="/signout-with-chatgpt?return_to=/">Sign out</a></header><section className="content" id="inventory"><div className="welcome"><div><span className="eyebrow">AMARAVATHI TOURS & TRAVEL</span><h2>Manage everything your guests can book.</h2><p>Keep hotels, cars, destinations and local experiences organised in one place.</p></div><button className="primary" onClick={startCreate}><Plus size={18}/>Add inventory</button></div>
 <div className="stats">{types.map(k=>{const Icon=icons[k];return <button key={k} onClick={()=>setType(k)} className={type===k?"stat selected":"stat"}><span><Icon size={20}/></span><div><strong>{counts[k]}</strong><small>{labels[k]}</small></div></button>})}</div>
 <div className="inventory-card"><div className="inventory-head"><div><h3>Inventory catalogue</h3><p>{filtered.length} {filtered.length===1?"item":"items"} shown</p></div><div className="tools"><label className="search"><Search size={17}/><span className="sr-only">Search inventory</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or location"/></label><select aria-label="Filter by type" value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{types.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></div></div>
 {filtered.length?<div className="item-list">{filtered.map(i=>{const Icon=icons[i.type];return <article className="item-row" key={i.id}><div className="thumb">{i.imageKey?<img src={`/api/media/${i.imageKey}`} alt=""/>:<Icon size={25}/>}</div><div className="item-main"><div><span className={`status ${i.status}`}>{i.status}</span><span className="type-label">{i.type}</span></div><h4>{i.name}</h4><p><MapPinned size={14}/>{i.location}</p></div><div className="price"><strong>{i.price==null?"Contact for price":`₹${i.price.toLocaleString("en-IN")}`}</strong><small>{i.price==null?"":"starting price"}</small></div><div className="actions"><button aria-label={`Edit ${i.name}`} onClick={()=>startEdit(i)}><Pencil size={17}/></button>{deleteId===i.id?<div className="confirm"><button disabled={busy} onClick={()=>remove(i.id)}>Delete</button><button onClick={()=>setDeleteId(null)}>Cancel</button></div>:<button className="danger" aria-label={`Delete ${i.name}`} onClick={()=>setDeleteId(i.id)}><Trash2 size={17}/></button>}</div></article>})}</div>:<div className="empty"><MapPinned size={34}/><h3>No inventory found</h3><p>Add your first item or change the current filter.</p><button className="primary" onClick={startCreate}><Plus size={18}/>Add inventory</button></div>}</div></section></main>
 {open&&<div className="drawer-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div className="drawer-head"><div><span className="eyebrow">INVENTORY EDITOR</span><h2 id="drawer-title">{editing?"Edit item":"Add inventory"}</h2></div><button aria-label="Close" onClick={()=>setOpen(false)}><X size={20}/></button></div><form onSubmit={save}><label>Category<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Name<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Riverfront Residency"/></label><label>Location<input required maxLength={100} value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="City or service area"/></label><label>Description<textarea maxLength={1500} rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Facilities, highlights and booking notes"/></label><div className="form-grid"><label>Starting price (₹)<input min="0" step="1" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Optional"/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label></div><label className="upload"><ImagePlus size={25}/><span><strong>Upload a cover image</strong><small>JPG, PNG or WebP up to 5 MB</small></span><input name="image" type="file" accept="image/*"/></label>{message&&<p className="form-message" role="alert">{message}</p>}<div className="form-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy?"Saving…":editing?"Save changes":"Create item"}</button></div></form></section></div>}</div>
}
